GET http://localhost:3000

###

GET http://localhost:3000/routes
###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "rota teste 1",
    "source_id": "source test 1",
    "destination": "destination test 1"
}

###

#Pegar o place if

GET http://localhost:3000/places?text=rua14 parque residencial das flores Anápolis Goias
